In [1]:
pip install imblearn

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('/content/data.csv')

In [4]:
df.head()

Unnamed: 0                                          statement   status
0           0                                         oh my gosh  Anxiety
1           1  trouble sleeping, confused mind, restless hear...  Anxiety
2           2  All wrong, back off dear, forward doubt. Stay ...  Anxiety
3           3  I've shifted my focus to something else but I'...  Anxiety
4           4  I'm restless and restless, it's been a month n...  Anxiety

In [5]:
df.drop(columns=["Unnamed: 0"],inplace=True)

In [6]:
df.head()

statement   status
0                                         oh my gosh  Anxiety
1  trouble sleeping, confused mind, restless hear...  Anxiety
2  All wrong, back off dear, forward doubt. Stay ...  Anxiety
3  I've shifted my focus to something else but I'...  Anxiety
4  I'm restless and restless, it's been a month n...  Anxiety

In [7]:
df.shape

(53043, 2)

In [8]:
df['status'].value_counts()

status
Normal                  16351
Depression              15404
Suicidal                10653
Anxiety                  3888
Bipolar                  2877
Stress                   2669
Personality disorder     1201
Name: count, dtype: int64

In [9]:
df.isna().sum()

statement    362
status         0
dtype: int64

In [10]:
df = df.dropna().reset_index(drop=True)

In [11]:
df.shape

(52681, 2)

In [12]:
df = df.drop_duplicates().reset_index(drop=True)

In [13]:
df['statement'][293]

"um! Pls, how do I feel afraid to go out of the house because I'm afraid to meet people, I don't know why, even though I wasn't like this before, I used to be nervous, then I'm so anxious I'm so sweaty"

In [14]:
df['status'].value_counts()

status
Normal                  16040
Depression              15094
Suicidal                10644
Anxiety                  3623
Bipolar                  2501
Stress                   2296
Personality disorder      895
Name: count, dtype: int64

In [15]:
df.shape

(51093, 2)

In [16]:
for i in range(5):
    print(df['statement'][i])

oh my gosh
trouble sleeping, confused mind, restless heart. All out of tune
All wrong, back off dear, forward doubt. Stay in a restless and restless place
I've shifted my focus to something else but I'm still worried
I'm restless and restless, it's been a month now, boy. What do you mean?


In [17]:
## lowercasing the words
df['statement'] = df['statement'].str.lower()

In [18]:
for i in range(5):
    print(df['statement'][i])

oh my gosh
trouble sleeping, confused mind, restless heart. all out of tune
all wrong, back off dear, forward doubt. stay in a restless and restless place
i've shifted my focus to something else but i'm still worried
i'm restless and restless, it's been a month now, boy. what do you mean?


In [19]:
import re

In [20]:
## remove unicode characters

def remove_unicode(txt):

    if isinstance(txt,str):
        return re.sub(r'[^\x00-\x7F]+', '', txt)
    return txt

In [21]:
df['cleaned'] = df['statement'].apply(lambda x:remove_unicode(x))

In [22]:
df.head()

statement   status  \
0                                         oh my gosh  Anxiety   
1  trouble sleeping, confused mind, restless hear...  Anxiety   
2  all wrong, back off dear, forward doubt. stay ...  Anxiety   
3  i've shifted my focus to something else but i'...  Anxiety   
4  i'm restless and restless, it's been a month n...  Anxiety   

                                             cleaned  
0                                         oh my gosh  
1  trouble sleeping, confused mind, restless hear...  
2  all wrong, back off dear, forward doubt. stay ...  
3  i've shifted my focus to something else but i'...  
4  i'm restless and restless, it's been a month n...

In [23]:
def clean(txt):
    if isinstance(txt,str):
        txt = re.sub(r"http[s]?://\S+|\[.*?\]\(.*?\)|@\w+", "", txt)
        txt = re.sub(r"[^a-zA-Z\s]","",txt)
        txt = re.sub(r"\s+"," ",txt).strip()
        return txt

    return txt

In [24]:
## removing special characters and whitespaces
df['cleaned'] = df['cleaned'].apply(lambda x:clean(str(x)))

In [25]:
df.head()

statement   status  \
0                                         oh my gosh  Anxiety   
1  trouble sleeping, confused mind, restless hear...  Anxiety   
2  all wrong, back off dear, forward doubt. stay ...  Anxiety   
3  i've shifted my focus to something else but i'...  Anxiety   
4  i'm restless and restless, it's been a month n...  Anxiety   

                                             cleaned  
0                                         oh my gosh  
1  trouble sleeping confused mind restless heart ...  
2  all wrong back off dear forward doubt stay in ...  
3  ive shifted my focus to something else but im ...  
4  im restless and restless its been a month now ...

In [26]:
import nltk
from nltk.tokenize import word_tokenize

In [27]:
## count word length
def count_words(txt):
    if isinstance(txt,str):
        count = len(word_tokenize(txt))
        return count
    return count

In [28]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [29]:
df['word_count'] = df['cleaned'].apply(lambda x:count_words(x))

In [30]:
df.head()

statement   status  \
0                                         oh my gosh  Anxiety   
1  trouble sleeping, confused mind, restless hear...  Anxiety   
2  all wrong, back off dear, forward doubt. stay ...  Anxiety   
3  i've shifted my focus to something else but i'...  Anxiety   
4  i'm restless and restless, it's been a month n...  Anxiety   

                                             cleaned  word_count  
0                                         oh my gosh           3  
1  trouble sleeping confused mind restless heart ...          10  
2  all wrong back off dear forward doubt stay in ...          14  
3  ive shifted my focus to something else but im ...          11  
4  im restless and restless its been a month now ...          14

In [31]:
from nltk.stem import PorterStemmer
stem = PorterStemmer()

In [32]:
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


True

In [33]:
from nltk.tokenize import word_tokenize

In [34]:
## tokenize
df['cleaned'] = df['cleaned'].apply(lambda x:word_tokenize(str(x)))

In [35]:
df.head()

statement   status  \
0                                         oh my gosh  Anxiety   
1  trouble sleeping, confused mind, restless hear...  Anxiety   
2  all wrong, back off dear, forward doubt. stay ...  Anxiety   
3  i've shifted my focus to something else but i'...  Anxiety   
4  i'm restless and restless, it's been a month n...  Anxiety   

                                             cleaned  word_count  
0                                     [oh, my, gosh]           3  
1  [trouble, sleeping, confused, mind, restless, ...          10  
2  [all, wrong, back, off, dear, forward, doubt, ...          14  
3  [ive, shifted, my, focus, to, something, else,...          11  
4  [im, restless, and, restless, its, been, a, mo...          14

#### Embedding generation

In [36]:
import torch
import torch.nn as nn
from collections import Counter


In [37]:
a=[]
for i in range(df['cleaned'].shape[0]):
    a.extend(df['cleaned'][i])

In [38]:
all_words = a

In [39]:
len(all_words)

5728844

In [40]:
word_counts = Counter(all_words)

In [41]:
len(word_counts) ## unique words

73134

In [42]:
word_to_index = {"<PAD>": 0, "<UNK>": 1}  # Padding and Unknown token
word_to_index.update({word: idx+2 for idx, (word, _) in enumerate(word_counts.most_common())})

In [43]:
vocab_size = len(word_to_index)

In [44]:
vocab_size

73136

In [45]:
def encode_sentences(sentence,word_to_index):

    indices = [word_to_index.get(word,word_to_index['<UNK>']) for word in sentence]

    if len(indices)<256: ##max length 256
        indices += [word_to_index['<PAD>']]*(256-len(indices))

    return indices[:256]

In [46]:
df['embeddings'] = df['cleaned'].apply(lambda x:encode_sentences(x,word_to_index))

In [47]:
df.head()

statement   status  \
0                                         oh my gosh  Anxiety   
1  trouble sleeping, confused mind, restless hear...  Anxiety   
2  all wrong, back off dear, forward doubt. stay ...  Anxiety   
3  i've shifted my focus to something else but i'...  Anxiety   
4  i'm restless and restless, it's been a month n...  Anxiety   

                                             cleaned  word_count  \
0                                     [oh, my, gosh]           3   
1  [trouble, sleeping, confused, mind, restless, ...          10   
2  [all, wrong, back, off, dear, forward, doubt, ...          14   
3  [ive, shifted, my, focus, to, something, else,...          11   
4  [im, restless, and, restless, its, been, a, mo...          14   

                                          embeddings  
0  [576, 6, 4613, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0...  
1  [907, 623, 938, 259, 1207, 291, 33, 44, 10, 80...  
2  [33, 270, 91, 142, 2210, 575, 1116, 335, 16, 7...  
3  [119, 6965, 6, 683, 3, 100, 178, 18, 46, 96, 4...  
4  [46, 1207, 4, 1207, 59, 41, 7, 283, 56, 1335, ...

In [48]:
word_to_index.get("gosh")

4613

In [49]:
df['embeddings'] = df['embeddings'].tolist()

In [50]:
df['status'].value_counts()

status
Normal                  16040
Depression              15094
Suicidal                10644
Anxiety                  3623
Bipolar                  2501
Stress                   2296
Personality disorder      895
Name: count, dtype: int64

In [51]:
df['status'] = df['status'].map({'Normal':int(0),'Depression':int(1),'Suicidal':int(2),'Anxiety':int(3),'Bipolar':int(4),'Stress':int(5),"Personality disorder":int(6)})

In [52]:
df['status'].value_counts()

status
0    16040
1    15094
2    10644
3     3623
4     2501
5     2296
6      895
Name: count, dtype: int64

In [53]:
df.head()

statement  status  \
0                                         oh my gosh       3   
1  trouble sleeping, confused mind, restless hear...       3   
2  all wrong, back off dear, forward doubt. stay ...       3   
3  i've shifted my focus to something else but i'...       3   
4  i'm restless and restless, it's been a month n...       3   

                                             cleaned  word_count  \
0                                     [oh, my, gosh]           3   
1  [trouble, sleeping, confused, mind, restless, ...          10   
2  [all, wrong, back, off, dear, forward, doubt, ...          14   
3  [ive, shifted, my, focus, to, something, else,...          11   
4  [im, restless, and, restless, its, been, a, mo...          14   

                                          embeddings  
0  [576, 6, 4613, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0...  
1  [907, 623, 938, 259, 1207, 291, 33, 44, 10, 80...  
2  [33, 270, 91, 142, 2210, 575, 1116, 335, 16, 7...  
3  [119, 6965, 6, 683, 3, 100, 178, 18, 46, 96, 4...  
4  [46, 1207, 4, 1207, 59, 41, 7, 283, 56, 1335, ...

In [54]:
df['embeddings'].values

array([list([576, 6, 4613, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
       list([907, 623, 938, 259, 1207, 291, 33, 44, 10, 8024, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [55]:
df.shape

(51093, 5)

In [56]:
Counter(df['word_count'].values<256)

Counter({np.True_: 45165, np.False_: 5928})

In [57]:
x = df.iloc[:,4].values
y = df.iloc[:,1].values

In [58]:
x.shape,y.shape

((51093,), (51093,))

In [64]:
from sklearn.model_selection import train_test_split

In [65]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [66]:
x_train.shape

(40874,)

In [ ]:
#x_train

array([list([9, 51, 26, 6, 177, 57, 165, 1775, 49, 69, 83, 373, 903, 53, 133, 9, 1497, 608, 680, 2, 15, 7, 1361, 78, 112, 197, 1775, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
       list([476, 8, 234, 53, 74, 72, 2, 27, 106, 16, 38, 222, 11, 21, 398, 9, 691, 3281, 16, 3, 3566, 4, 77, 184, 20, 172, 764, 2, 15, 3580, 505, 23, 43, 19, 8, 77, 2686, 210, 3

In [ ]:
##import numpy as np
##from sklearn.utils.class_weight import compute_class_weight
#class_weights = compute_class_weight(class_weight='balanced', classes=np.unique(y_train), y=y_train)
#class_weight_dict = dict(enumerate(class_weights)))

In [ ]:
#class_weight_dict

In [ ]:
#class_weights = torch.tensor(class_weights,dtype=torch.float32)

In [67]:
x_train = torch.tensor(list(x_train),dtype=torch.long)
x_test = torch.tensor(list(x_test),dtype=torch.long)

In [68]:
y_train = torch.tensor(y_train,dtype=torch.long)

In [69]:
y_test = torch.tensor(y_test,dtype=torch.long)

In [70]:
x_train.shape

torch.Size([40874, 256])

In [79]:
from torch.utils.data import Dataset,DataLoader

## dataset class
class CustomDataset(Dataset):

    def __init__(self,features,labels):
        self.features = features
        self.labels = labels

    def __len__(self):
        return len(self.features)

    def __getitem__(self,idx):
        return self.features[idx],self.labels[idx]

In [102]:
train_dataset = CustomDataset(x_train,y_train)
test_dataset = CustomDataset(x_test,y_test)

In [103]:
len(train_dataset)

40874

In [104]:
train_loader = DataLoader(train_dataset,batch_size=128,drop_last=True)
test_loader = DataLoader(test_dataset,batch_size=128,drop_last=True)

In [105]:
import torch.nn as nn

class LSTMModel(nn.Module):
    def __init__(self, vocab_size, embedding_dim, hidden_dim, output_dim, num_layers=2, dropout=0.5):
        super().__init__()

        # Embedding Layer
        self.embedding = nn.Embedding(vocab_size, embedding_dim)

        # LSTM Layer (Stacked + Bidirectional)
        self.lstm = nn.LSTM(
            input_size=embedding_dim,
            hidden_size=hidden_dim,
            num_layers=num_layers,
            batch_first=True,
            bidirectional=True,
            dropout=dropout
        )

        # Batch Normalization Layer
        self.batch_norm = nn.BatchNorm1d(hidden_dim * 2)  # Normalize across features

        # Fully Connected Layer
        self.fc = nn.Linear(hidden_dim * 2, output_dim)  # Multiply by 2 for bidirectional

        # Dropout Layer for Regularization
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        x = self.embedding(x)  # Convert words to embeddings
        lstm_out, (hidden, _) = self.lstm(x)  # Run through LSTM

        # Get the last hidden state from both directions
        hidden = torch.cat((hidden[-2], hidden[-1]), dim=1)  # Concatenate last forward & backward hidden states

        # Apply Batch Normalization
        hidden = self.batch_norm(hidden)

        # Apply Dropout before passing to the FC layer
        output = self.fc(self.dropout(hidden))

        return output

In [106]:
learning_rate = 0.01
epochs = 50

In [107]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")

Using device: cuda


In [108]:
## create model
model = LSTMModel(vocab_size=vocab_size,embedding_dim=256,hidden_dim=64,output_dim=7).to(device)

In [109]:
import torch.optim as optim

## loss
criterion = nn.CrossEntropyLoss()

## optimizer
optimizer = optim.Adam(model.parameters(),lr=learning_rate)

In [110]:
for i in range(epochs):

    total_epoch_loss = 0

    for batch_features,batch_labels in train_loader:
        batch_features = batch_features.long().to(device)
        batch_labels = batch_labels.long().to(device)

        ## forward pass
        y_preds = model(batch_features)

        ## loss calculation
        loss = criterion(y_preds,batch_labels)

        ## clearing grads
        optimizer.zero_grad()

        ## backward pass
        loss.backward()

        ## update weights
        optimizer.step()

        total_epoch_loss += loss.item()

    mean_loss = total_epoch_loss/len(train_loader)

    print(f" Epoch : {i+1}  Average Loss : {mean_loss}")

 Epoch : 1  Average Loss : 0.9449663661116716
 Epoch : 2  Average Loss : 0.6605938565581569
 Epoch : 3  Average Loss : 0.5748637079445172
 Epoch : 4  Average Loss : 0.5300681114570475
 Epoch : 5  Average Loss : 0.5058804008654293
 Epoch : 6  Average Loss : 0.47964989718598633
 Epoch : 7  Average Loss : 0.4630035000348166
 Epoch : 8  Average Loss : 0.44438537787120547
 Epoch : 9  Average Loss : 0.44585512443022296
 Epoch : 10  Average Loss : 0.45073495081225906
 Epoch : 11  Average Loss : 0.4246278761135747
 Epoch : 12  Average Loss : 0.40429850525243155
 Epoch : 13  Average Loss : 0.3995079838650354
 Epoch : 14  Average Loss : 0.3905979311765175
 Epoch : 15  Average Loss : 0.38141544677060224
 Epoch : 16  Average Loss : 0.37947725497629947
 Epoch : 17  Average Loss : 0.3727323461942912
 Epoch : 18  Average Loss : 0.3666330981404056
 Epoch : 19  Average Loss : 0.36820849986472476
 Epoch : 20  Average Loss : 0.35801389794738314
 Epoch : 21  Average Loss : 0.3532537066357263
 Epoch : 22  

In [111]:
from sklearn.metrics import classification_report, confusion_matrix
import numpy as np

def evaluate_model(model, dataloader, criterion, class_names=None):
    model.eval()  # Set to evaluation mode
    device = next(model.parameters()).device  # Get model's device

    all_preds = []
    all_labels = []
    total_loss = 0

    with torch.no_grad():
        for batch_features, batch_labels in dataloader:
            # Move data to the same device as model
            batch_features = batch_features.long().to(device)
            batch_labels = batch_labels.long().to(device)

            # Forward pass
            outputs = model(batch_features)
            loss = criterion(outputs.to(device), batch_labels)
            total_loss += loss.item()

            # Get predictions
            _, preds = torch.max(outputs, 1)

            # Store for metrics
            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(batch_labels.cpu().numpy())

    # Calculate metrics
    avg_loss = total_loss / len(dataloader)
    accuracy = (np.array(all_preds) == np.array(all_labels)).mean()

    print(f"\nEvaluation Loss: {avg_loss:.4f}, Accuracy: {accuracy:.4f}")

    # Classification Report
    print("\nClassification Report:")
    print(classification_report(
        all_labels,
        all_preds,
        target_names=class_names,  # Optional: pass class names
        digits=4
    ))

    # Confusion Matrix
    print("\nConfusion Matrix:")
    print(confusion_matrix(all_labels, all_preds))

    return {
        'loss': avg_loss,
        'accuracy': accuracy,
        'report': classification_report(all_labels, all_preds, output_dict=True)
    }

In [112]:
# Example class names (replace with your actual class names)
class_names = ["Class_0", "Class_1", "Class_2", "Class_3", "Class_4", "Class_5", "Class_6"]

# Run evaluation
results = evaluate_model(
    model=model,
    dataloader=test_loader,
    criterion=criterion,
    class_names=class_names  # Optional
)



Evaluation Loss: 0.8300, Accuracy: 0.7388

Classification Report:
              precision    recall  f1-score   support

     Class_0     0.8810    0.9154    0.8979      3097
     Class_1     0.7058    0.6809    0.6931      3027
     Class_2     0.6181    0.6281    0.6231      2100
     Class_3     0.7083    0.8035    0.7529       692
     Class_4     0.8090    0.7292    0.7670       517
     Class_5     0.5173    0.4969    0.5069       481
     Class_6     0.6614    0.4242    0.5169       198

    accuracy                         0.7388     10112
   macro avg     0.7001    0.6683    0.6797     10112
weighted avg     0.7369    0.7388    0.7368     10112


Confusion Matrix:
[[2835   78   62   56    8   55    3]
 [ 115 2061  711   42   38   45   15]
 [ 112  642 1319   12    3   12    0]
 [  37   35    7  556   13   37    7]
 [  16   35    6   35  377   38   10]
 [  86   42   19   70   17  239    8]
 [  17   27   10   14   10   36   84]]


In [114]:
torch.save(model,"lstm.pth")

In [119]:
model1 = torch.load("/content/lstm.pth",weights_only=False)

In [120]:
results = evaluate_model(
    model=model1,
    dataloader=test_loader,
    criterion=criterion,
    class_names=class_names  # Optional
)


Evaluation Loss: 0.8300, Accuracy: 0.7388

Classification Report:
              precision    recall  f1-score   support

     Class_0     0.8810    0.9154    0.8979      3097
     Class_1     0.7058    0.6809    0.6931      3027
     Class_2     0.6181    0.6281    0.6231      2100
     Class_3     0.7083    0.8035    0.7529       692
     Class_4     0.8090    0.7292    0.7670       517
     Class_5     0.5173    0.4969    0.5069       481
     Class_6     0.6614    0.4242    0.5169       198

    accuracy                         0.7388     10112
   macro avg     0.7001    0.6683    0.6797     10112
weighted avg     0.7369    0.7388    0.7368     10112


Confusion Matrix:
[[2835   78   62   56    8   55    3]
 [ 115 2061  711   42   38   45   15]
 [ 112  642 1319   12    3   12    0]
 [  37   35    7  556   13   37    7]
 [  16   35    6   35  377   38   10]
 [  86   42   19   70   17  239    8]
 [  17   27   10   14   10   36   84]]
